language: php

php:
  - 5.4

script:
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev && vendor/bin/phpunit --configuration tests/phpunit.xml

services: mongodb